/**
 * The stretch sync journal. State on a device = replay(legacy, ops):
 * the frozen legacy base (progress from before this build) plus the op
 * journal. Ops are immutable and idempotent (deduped by `id` on merge),
 * so sync is a matter of exchanging unseen ops.
 */

export type EntityKind = "plankDay" | "challenge" | "session" | "settings" | "reset";

export type OpKind = "create" | "patch";

export interface Op {
  // Idempotency key (UUIDv4, generated by the creating device)
  id: string;
  // Hybrid logical clock, sortable string (see hlc.ts)
  hlc: string;
  // Device that created the op; breaks ties between equal clocks
  device: string;
  entity: EntityKind;
  // plankDay: YYYY-MM-DD · challenge: "plank" · session: session id
  // settings: "app" · reset: "all"
  entityId: string;
  kind: OpKind;
  data?: Record<string, unknown>;
}

/**
 * Progress from before the sync build, frozen into localStorage once on
 * upgrade. It acts as the base layer of the replay and is never pushed to
 * the server (it stays on this device).
 */
export interface LegacyBase {
  plank: { startedAt: string | null; days: { date: string; seconds: number }[] };
  sessions: { id: string; routineId: string; routineTitle: string; duration: number; completedAt: string }[];
  settings: { theme: "light" | "dark" | "system"; soundEnabled: boolean; hapticEnabled: boolean };
}

/** One op's server-side rejection reason (returned with a 400 push). */
export interface InvalidOp {
  id: string;
  error: string;
}
